apiVersion: {{ include "poddisruptionbudgetversion" .}}
kind: PodDisruptionBudget
metadata:
  name: blackbox-exporter
  namespace: kube-system
spec:
  maxUnavailable: 1
  selector:
    matchLabels:
      component: blackbox-exporter